-- MySQL Script generated by MySQL Workbench
-- Sun Apr  8 17:11:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema conan_crawler
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `conan_crawler` ;

-- -----------------------------------------------------
-- Schema conan_crawler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conan_crawler` DEFAULT CHARACTER SET utf8 ;
USE `conan_crawler` ;

-- -----------------------------------------------------
-- Table `conan_crawler`.`key_word_tb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conan_crawler`.`key_word_tb` ;

CREATE TABLE IF NOT EXISTS `conan_crawler`.`key_word_tb` (
  `id` VARCHAR(45) NOT NULL,
  `key_word` VARCHAR(45) NOT NULL COMMENT '关键词',
  `crt_user` VARCHAR(45) NOT NULL COMMENT '创建人',
  `crt_time` DATETIME NOT NULL COMMENT '创建时间',
  `status` VARCHAR(1) NOT NULL DEFAULT 0 COMMENT '0 待扫描\n1 正在扫描\n2 扫描完毕',
  `crt_ip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_word_UNIQUE` (`key_word` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '关键词表';


-- -----------------------------------------------------
-- Table `conan_crawler`.`key_word_scan_tb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conan_crawler`.`key_word_scan_tb` ;

CREATE TABLE IF NOT EXISTS `conan_crawler`.`key_word_scan_tb` (
  `id` VARCHAR(45) NOT NULL,
  `key_word` VARCHAR(45) NOT NULL,
  `item_id` VARCHAR(45) NOT NULL,
  `item_title` VARCHAR(45) NOT NULL,
  `user_number_id` VARCHAR(45) NOT NULL,
  `shop_type` VARCHAR(45) NOT NULL DEFAULT 0 COMMENT '0 天猫\n1 淘宝',
  `crt_time` DATETIME NOT NULL,
  `crt_user` VARCHAR(45) NOT NULL,
  `crt_ip` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hash_UNIQUE` (`key_word` ASC, `item_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '关键词扫描结果表';


-- -----------------------------------------------------
-- Table `conan_crawler`.`goods_tb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conan_crawler`.`goods_tb` ;

CREATE TABLE IF NOT EXISTS `conan_crawler`.`goods_tb` (
  `id` VARCHAR(45) NOT NULL,
  `item_id` VARCHAR(45) NOT NULL,
  `item_title` VARCHAR(45) NOT NULL,
  `user_number_id` VARCHAR(45) NOT NULL,
  `shop_type` VARCHAR(45) NOT NULL,
  `crt_user` VARCHAR(45) NOT NULL,
  `crt_time` DATETIME NOT NULL,
  `crt_ip` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `goods_UNIQUE` (`item_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '商品表 包含商品id和商家id';


-- -----------------------------------------------------
-- Table `conan_crawler`.`seller_tb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conan_crawler`.`seller_tb` ;

CREATE TABLE IF NOT EXISTS `conan_crawler`.`seller_tb` (
  `id` VARCHAR(45) NOT NULL,
  `user_number_id` VARCHAR(45) NOT NULL,
  `shop_type` VARCHAR(45) NOT NULL DEFAULT 0 COMMENT '0 天猫\n1 ',
  `crt_user` VARCHAR(45) NOT NULL,
  `crt_time` DATETIME NOT NULL,
  `crt_ip` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_number_id_UNIQUE` (`user_number_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conan_crawler`.`shop_scan_tb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conan_crawler`.`shop_scan_tb` ;

CREATE TABLE IF NOT EXISTS `conan_crawler`.`shop_scan_tb` (
  `id` VARCHAR(45) NOT NULL,
  `shop_id` VARCHAR(45) NOT NULL,
  `shop_name` VARCHAR(45) NOT NULL COMMENT '店铺名称',
  `seller_nick` VARCHAR(45) NULL,
  `shop_star` VARCHAR(45) NULL,
  `dsr_desc` VARCHAR(45) NULL,
  `dsr_serv` VARCHAR(45) NULL,
  `dsr_logi` VARCHAR(45) NULL,
  `user_number_id` VARCHAR(45) NOT NULL,
  `crt_user` VARCHAR(45) NOT NULL,
  `crt_time` DATETIME NOT NULL,
  `crt_ip` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `shop_id_UNIQUE` (`shop_id` ASC))
ENGINE = InnoDB
COMMENT = '店铺扫描信息';


-- -----------------------------------------------------
-- Table `conan_crawler`.`comment_tb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conan_crawler`.`comment_tb` ;

CREATE TABLE IF NOT EXISTS `conan_crawler`.`comment_tb` (
  `id` VARCHAR(45) NOT NULL,
  `item_id` VARCHAR(45) NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  `crt_user` VARCHAR(45) NOT NULL,
  `crt_time` DATETIME NOT NULL,
  `crt_ip` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `goods_id_UNIQUE` (`item_id` ASC))
ENGINE = InnoDB
COMMENT = '评论数表';


-- -----------------------------------------------------
-- Table `conan_crawler`.`comment_scan_tb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conan_crawler`.`comment_scan_tb` ;

CREATE TABLE IF NOT EXISTS `conan_crawler`.`comment_scan_tb` (
  `id` VARCHAR(45) NOT NULL,
  `item_id` VARCHAR(45) NOT NULL,
  `buyer_nick` VARCHAR(45) NOT NULL,
  `first_review_time` VARCHAR(45) NOT NULL,
  `review_content` VARCHAR(45) NOT NULL,
  `is_super_vip` VARCHAR(45) NOT NULL,
  `buyer_star` VARCHAR(45) NOT NULL,
  `crt_time` DATETIME NOT NULL,
  `crt_user` VARCHAR(45) NOT NULL,
  `crt_ip` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `bussiness_UNIQUE` (`item_id` ASC, `buyer_nick` ASC, `first_review_time` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
