package com.conan.crawler.server.post.mapper;

import com.conan.crawler.server.post.entity.CommentScanTb;

public interface CommentScanTbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_scan_tb
     *
     * @mbg.generated Sat Apr 07 22:39:14 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_scan_tb
     *
     * @mbg.generated Sat Apr 07 22:39:14 CST 2018
     */
    int insert(CommentScanTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_scan_tb
     *
     * @mbg.generated Sat Apr 07 22:39:14 CST 2018
     */
    int insertSelective(CommentScanTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_scan_tb
     *
     * @mbg.generated Sat Apr 07 22:39:14 CST 2018
     */
    CommentScanTb selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_scan_tb
     *
     * @mbg.generated Sat Apr 07 22:39:14 CST 2018
     */
    int updateByPrimaryKeySelective(CommentScanTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_scan_tb
     *
     * @mbg.generated Sat Apr 07 22:39:14 CST 2018
     */
    int updateByPrimaryKey(CommentScanTb record);
}