package com.conan.crawler.server.post.mapper;

import com.conan.crawler.server.post.entity.GoodsTb;

public interface GoodsTbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tb
     *
     * @mbg.generated Sun Apr 01 12:16:23 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tb
     *
     * @mbg.generated Sun Apr 01 12:16:23 CST 2018
     */
    int insert(GoodsTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tb
     *
     * @mbg.generated Sun Apr 01 12:16:23 CST 2018
     */
    int insertSelective(GoodsTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tb
     *
     * @mbg.generated Sun Apr 01 12:16:23 CST 2018
     */
    GoodsTb selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tb
     *
     * @mbg.generated Sun Apr 01 12:16:23 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tb
     *
     * @mbg.generated Sun Apr 01 12:16:23 CST 2018
     */
    int updateByPrimaryKey(GoodsTb record);
}