package com.conan.crawler.server.post.mapper;

import com.conan.crawler.server.post.entity.KeyWordTb;

public interface KeyWordTbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:12:42 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:12:42 CST 2018
     */
    int insert(KeyWordTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:12:42 CST 2018
     */
    int insertSelective(KeyWordTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:12:42 CST 2018
     */
    KeyWordTb selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:12:42 CST 2018
     */
    int updateByPrimaryKeySelective(KeyWordTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:12:42 CST 2018
     */
    int updateByPrimaryKey(KeyWordTb record);
}