package com.conan.crawler.server.post.mapper;

import java.util.List;

import com.conan.crawler.server.post.entity.ShopTb;

public interface ShopTbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:14:44 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:14:44 CST 2018
     */
    int insert(ShopTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:14:44 CST 2018
     */
    int insertSelective(ShopTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:14:44 CST 2018
     */
    ShopTb selectByPrimaryKey(String id);
    
    List<String> selectShopName();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:14:44 CST 2018
     */
    int updateByPrimaryKeySelective(ShopTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tb
     *
     * @mbg.generated Thu Apr 05 11:14:44 CST 2018
     */
    int updateByPrimaryKey(ShopTb record);
}