server:
  port: 8082

spring:
  datasource:
    url : jdbc:mysql://118.24.173.247:3306/conan_crawler?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false  
    username : root  
    password : guo@dong  
    driverClassName : com.mysql.jdbc.Driver
    
logging:
    path: ../log-post
    level:
        org.springframework.web: TRACE
        guru.springframework.controllers: TRACE
        com.dy.springboot.server.mapper: DEBUG
        

